RESOURCE_TICK_SECONDS = 60
STRATEGIC_TICK_SECONDS = 5
MOVEMENT_TICK_SECONDS = 1
AP_MAX = 200
AP_REGEN_PER_MINUTE = 20
AP_REGEN_PERIOD_SECONDS = 60.0 / AP_REGEN_PER_MINUTE
DOCTRINES = ("assault", "siege", "defense")
MAX_HP = 100
